fix error C2057: expected constant expression --> MSVC does not support this GCC-specific idiom for semi-dynamically allocating arrays on the stack:
```
const int size = 42;
int array[size];
```

nor does it support

```
int func(int size) {
  int array[size];
  //...
}
```